version: "3.7"

services:
  database:
    #ESSE É O NOME DO SERVICE QUE DEVE ESTAR NO ARQUIVO DE CRIAÇÃO DE CONEXÃO
    image: postgres
    container_name: database_ignite
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=rentx
      - TZ="America/Sao_Paulo"
    volumes:
      - pgdata:/data/postgres

  redis:
    image: redis:alpine
    ports:
      - 6379:6379

  app:
    build: .
    environment:
      - TZ="America/Sao_Paulo"
    container_name: rentx
    ports:
      - 3333:3333
      - 9229:9229 #Você pode inserir essa porta tbm pra poder usar o debug
    volumes:
      - .:/usr/app
    links:
      #faz uma ligação entre os containers,  permitindo que o container de destino (api) tenha informações do container de origem(database)
      - database
    depends_on:
      #irá informar que nosso serviço de api irá depender do serviço do banco de dados (database)
      - database

volumes:
  pgdata:
    driver: local
