name: CI

on:
  push:
    branches: [ main ]
  
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 16
          
      - name: Install Dependencies
        run: npm install
      
      - name: Build
        run: npm run build
        
        # SCP Files - Transferências de arquivo via ssh
      - uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          # Quais pastas/arquivos que queremos copiar
          source: "., !node_modules, !src/shared/infra/typeorm/index.ts, !docker-compose.yml"
          target: "~/app/rentx"
          
      - name: Update API
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/app/rentx
            npm install
            ./node_modules/.bin/typeorm migration:run
            pm2 restart rentx_api
        
